### ISSUE TITLE
enforceLogback() removes transitive logback-core dependency

### ISSUE THREAD

**Issue by nakamorichi** [ljacomet/logging-capabilities#12]
# Issue
Having 
```
loggingCapabilities {
    enforceLogback()
}
```
removes transitive dependency of logback-core.

# Expected behavior
enforceLogback() does not remove transitive logback-core dependency.

# Environment
logging-capabilities: 0.9.0
Gradle: 7.2

**Comment by ljacomet** [comment]
Hello,

Thank you for your interest in this plugin.
Any chance you can provide a reproducer?
I fail to see how enforcing logback would cause one of its dependencies to be removed.

**Comment by nakamorichi** [comment]
Hi.

I tried to reproduce in different project but was unable to. I guess the issue is caused by some other interfering Gradle plugins. I will continue finding a way to reproduce.

Btw, thanks for the plugin. Actually found out about this due to the recent log4j vulnerability and the need to enforce correct logging dependencies.

**Comment by nakamorichi** [comment]
The issue seems to be related to usage of io.spring.dependency-management plugin. When using Gradle platform syntax instead of the plugin's dependencyManagement, the issue doesn't occur. I'll try to create reproducible sample later.

**Comment by ljacomet** [comment]
I am going to close this one as duplicate of #17, mostly because that other title describes the source of the issue. Thanks for the report.
