### ISSUE TITLE
Support Log4j 2 implementations

### ISSUE THREAD

**Issue by jdai8** [ljacomet/logging-capabilities#13]
Log4j 2 [docs](https://logging.apache.org/log4j/2.x/faq.html#which_jars) suggest that `org.apache.logging.log4j:log4j-core` and `org.apache.logging.log4j:log4j-to-slf4j` are mutually exclusive, as both represent a "Log4j 2 implementation".

If I understand correctly, the current capabilities aren't sufficient to model this. Would it make sense to introduce a `log4j2-impl` capability that models this relationship? One timely use case is routing Log4j 2 callsites to slf4j instead of `log4j-core`.

**Comment by ljacomet** [comment]
Hello,

Thank you for your interest in this plugin.

I believe you are right and by not accounting for `log4j-core` in the plugin, I missed that exclusion.

**Comment by jdai8** [comment]
I think this would require:

- Adding a new capability that looks like:

| Capability  | Impacted modules | Comment
| ------------- | ------------- | --------- |
| `log4j2-impl` | `org.apache.logging.log4j:log4j-core`, `org.apache.logging.log4j:log4j-to-slf4j` | Represents a Log4j 2 implementation


- Introducing a `selectLog4J2Implementation`.
- Making `enforceLogback` and `enforceSlf4JSimple` select `org.apache.logging.log4j:log4j-to-slf4j`
- Making `enforceLog4J2` select `org.apache.logging.log4j:log4j-core`

Note that the last two would be breaking changes.

If this all sounds correct, I'm happy to try implementing this.

**Comment by ljacomet** [comment]
Thanks for the proposal but I had time this weekend so I took care of it.
Wrapping a couple other improvements and there should be a release later today or in the coming days.
