### ISSUE TITLE
Extra Slf4J provider: redshift-jdbc42

### ISSUE THREAD

**Issue by ljacomet** [ljacomet/logging-capabilities#2]
Looks like `com.amazon.redshift:redshift-jdbc42:1.2.37.1061` at least comes with a bundled Slf4J binding `org.slf4j.impl.StaticLoggerBinder`.

* Investigate which versions are affected
* Decide whether or not this means the library must be accounted for by this plugin

**Comment by Vampire** [comment]
That's by far not the only one: https://search.maven.org/search?q=fc:org.slf4j.impl.StaticLoggerBinder

**Comment by ljacomet** [comment]
Replaced by:
* gradlex-org/jvm-dependency-conflict-resolution#165
