### ISSUE TITLE
Extend plugin functionality to also add logging framework dependencies

### ISSUE THREAD

**Issue by rpalcolea** [ljacomet/logging-capabilities#3]
The current state of the plugin allows folks to do the following:

```
loggingCapabilities {
    enforceLog4J2()
}
```

This is fantastic as it allows to replace other frameworks such as logback:

```
+--- ch.qos.logback:logback-classic:1.+ -> org.apache.logging.log4j:log4j-slf4j-impl:2.13.0
|    +--- org.slf4j:slf4j-api:1.7.25 -> 2.0.0-alpha1
|    +--- org.apache.logging.log4j:log4j-api:2.13.0
|    \--- org.apache.logging.log4j:log4j-core:2.13.0
|         \--- org.apache.logging.log4j:log4j-api:2.13.0
+--- ch.qos.logback:logback-core:1.+ -> 1.3.0-alpha5
|    \--- edu.washington.cs.types.checker:checker-framework:1.7.0
+--- org.slf4j:slf4j-api:1.+ -> 2.0.0-alpha1
+--- org.slf4j:slf4j-log4j12:latest.release -> org.apache.logging.log4j:log4j-slf4j-impl:2.13.0 (*)
+--- org.apache.logging.log4j:log4j-core:2.13.0 (*)
\--- org.apache.logging.log4j:log4j-slf4j-impl:2.13.0 (*)
``` 

However, it is necessary that users add the log4j dependencies explicitly.

It would be great if the plugin allowed to add those also. A few things to consider (I guess).

* Being able to set the version of the logging framework and have a sane default in case users don't want to set one
* Being able to collaborate with recommendations (BOMs/ gradle platforms) so folks can decide to just apply this plugin and then the recommendations would provide the guidance on which version to use. Hopefully this could play well with https://github.com/nebula-plugins/nebula-dependency-recommender-plugin

**Comment by ljacomet** [comment]
I've done some thinking around that and I think I prefer keeping the feature as-is.

The plugin detects conflicts, can handle substitutions when enforcing (bugged for log4j2 up to 0.11.0, see #35) but does not add dependencies.

Adding a dependency is really something that belongs in the project, or in its convention plugins. Not in a binary plugin where finding what's added is complicated.

So closing as won't fix.
