### ISSUE TITLE
Enforcement no longer works with spring-jcl

### ISSUE THREAD

**Issue by cmuchinsky** [ljacomet/logging-capabilities#36]
The recent change to handle `spring-jcl` has caused a regression when using `enforceLogback`. After updating lockfiles I now see that `spring-jcl` has been removed from `runtimeClasspath`, however it is left intact for `compileClasspath`, which causes this problem during build time:
```
> Could not resolve all files for configuration ':foo:compileClasspath'.
   > Did not resolve 'org.springframework:spring-jcl:5.3.26' which is part of the dependency lock state
   > Resolved 'org.slf4j:jcl-over-slf4j:1.7.36' which is not part of the dependency lock state
```

**Comment by ljacomet** [comment]
Thank you for your interest in this plugin.

I would have asked for a reproducer, but a PR with a test is great as well.
