### ISSUE TITLE
Make the plugin aware of `ch.qos.reload4j:reload4j`

### ISSUE THREAD

**Issue by erdi** [ljacomet/logging-capabilities#38]
`ch.qos.reload4j:reload4j` is a log4j 1.x drop in replacement based on log4j `1.2.17` aiming to not contain any vulnerabilities.

I believe that all it takes to make the plugin aware of it is to add `slf4j-vs-log4j2-log4j` capability to that module. Would you be interested in a PR with that plus any necessary test and docs changes?

**Comment by ljacomet** [comment]
Hi @erdi ,

Thank you for your interest in the plugin. A PR is most definitely welcome.

**Comment by ljacomet** [comment]
Replaced by:
* gradlex-org/jvm-dependency-conflict-resolution#162
