### ISSUE TITLE
Make the plugin aware of JBoss Logging

### ISSUE THREAD

**Issue by erdi** [ljacomet/logging-capabilities#39]
[JBoss Logging](https://github.com/jboss-logging/jboss-logging) is yet another logging facade. It would be nice if the plugin was made aware of it. I believe that the following modules would need to have metadata/capabilities attached to them by the plugin:
- `org.jboss.logmanager:jboss-logmanager`
- `org.jboss.logmanager:jboss-logmanager-log4j`
- `org.jboss.logmanager:log4j-jboss-logmanager`
- `org.jboss.slf4j:slf4j-jboss-logmanager`
- `org.jboss.slf4j:slf4j-jboss-logging`
- `org.jboss.logmanager:log4j2-jboss-logmanager`
- `org.jboss.logmanager:commons-logging-jboss-logmanager`
- `org.jboss.logging:commons-logging-jboss-logging`

I would be willing to work on a PR for the above if that's something of interest for the maintainers.

**Comment by ljacomet** [comment]
Hi @erdi,

The broader support, the better. So PR is welcome. Given the number of modules involved, it might be good to also document here the design, indicating which capabilities are needed for these modules.

**Comment by erdi** [comment]
Good point about documenting the design here before working on a PR.

This is what I'm thinking:

| Module | Capabilities | Notes |
| --- | --- | --- |
| `org.jboss.logmanager:jboss-logmanager` | `slf4j-vs-log4j2-jul` | Should the capability be renamed to `jul-impl`? Or something else? Basically `org.slf4j:jul-to-slf4j`, `org.apache.logging.log4j:log4j-jul` and `org.jboss.logmanager:jboss-logmanager` are not compatible with one another because they either use a custom `java.util.logging.LogManager` implementation or modify the global root logger |
| `org.jboss.logmanager:log4j-jboss-logmanager` | `slf4j-vs-log4j2-log4j` | Should the capability name be changed to `slf4j-vs-log4j2-vs-jboss-log4j`? Or maybe just `log4j-impl`? The latter will also make it easier to cater for `reload4j` as per  #38. |
| `org.jboss.logmanager:jboss-logmanager-log4j` | `slf4j-vs-log4j2-log4j` | This looks like an old version of `org.jboss.logmanager:log4j-jboss-logmanager` |
| `org.jboss.slf4j:slf4j-jboss-logmanager` | `slf4j-impl` |
| `org.jboss.slf4j:slf4j-jboss-logging` | `slf4j-impl` |
| `org.jboss.logmanager:log4j2-jboss-logmanager` | `log4j2-impl` |
| `org.jboss.logmanager:commons-logging-jboss-logmanager` | `commons-logging-impl` |
| `org.jboss.logging:commons-logging-jboss-logging` | `commons-logging-impl` |

Any thoughts about that, @ljacomet? The last 4 are straightforward but for the ones with notes I will probably need some guidance from you, I'm not sure about the backwards compatibility contract this plugin has for capability names given it's pre `1.x`....

**Comment by ljacomet** [comment]
Replaced with:
* gradlex-org/jvm-dependency-conflict-resolution#161
