### ISSUE TITLE
Impossible to enable alignment on Gradle 6.2 or later.

### ISSUE THREAD

**Issue by kreiger** [ljacomet/logging-capabilities#6]
In the fix to #4 you have the code 

```
if (gradleVersion.compareTo(GRADLE_5_2) < 0 && gradleVersion.compareTo(GRADLE_6_2) >= 0) {
    configureAlignment(dependencies);
}
```
See https://github.com/ljacomet/logging-capabilities/commit/ab3fb780054c2271fa27700c624f58402262e5f7#r37521179

`gradleVersion < '5.2'` *AND* `gradleVersion >= '6.2'` ?

Isn't this always false?

Further, `enableAlignment()` only works if Gradle version is less than 6.2.

This makes it impossible to enable alignment on Gradle 6.2 or later.

**Comment by jordanjennings** [comment]
We are seeing this also with Gradle 6.2, there's no way to have the plugin align versions and it's causing some hard to detect brokenness.

**Comment by ljacomet** [comment]
🤦‍♂ well, my mistake.
will fix _and_ add multi version tests

**Comment by ljacomet** [comment]
Ended up pushing a new version since the change is so small. Which means adding the tests will not delay the fix.
